## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則話來觀察訓練情形。

In [1]:
from sklearn import datasets
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import Lasso, Ridge, LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Linear Regression

In [2]:
boston = datasets.load_boston()

x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.1, random_state=4)

linreg = LinearRegression()

linreg.fit(x_train, y_train)

y_pred = linreg.predict(x_test)

MSE = mean_squared_error(y_test, y_pred)

r2 = r2_score(y_test, y_pred)

print("Mean squred error: ", MSE)
print("r2 score: ", r2)

Mean squred error:  17.038701324921963
r2 score:  0.7926083526613232


In [3]:
linreg.coef_

array([-1.25856659e-01,  4.84257396e-02,  1.84085281e-02,  3.08509569e+00,
       -1.73277018e+01,  3.61674713e+00,  2.19181853e-03, -1.49361132e+00,
        3.19979200e-01, -1.27294649e-02, -9.27469086e-01,  9.50912468e-03,
       -5.33592471e-01])

# L1: Lasso Regression

In [4]:
boston = datasets.load_boston()

x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.1, random_state=4)

Lasso1 = Lasso(alpha = 0.5)

Lasso1.fit(x_train, y_train)

y_pred = Lasso1.predict(x_test)

MSE = mean_squared_error(y_test, y_pred)

r2 = r2_score(y_test, y_pred)

print("Mean squred error: ", MSE)
print("r2 score: ", r2)

Mean squred error:  19.657534153658876
r2 score:  0.7607324459182463


In [5]:
Lasso1.coef_

array([-0.09756158,  0.05137582, -0.        ,  0.        , -0.        ,
        2.34951302,  0.00488326, -0.96493883,  0.28915606, -0.01571844,
       -0.74854279,  0.00957598, -0.66798612])

In [6]:
Lasso2 = Lasso(alpha = 0.05)

Lasso2.fit(x_train, y_train)

y_pred = Lasso2.predict(x_test)

MSE = mean_squared_error(y_test, y_pred)

r2 = r2_score(y_test, y_pred)

print("Mean squred error: ", MSE)
print("r2 score: ", r2)

Mean squred error:  18.168396720023477
r2 score:  0.7788579274080598


In [7]:
Lasso2.coef_

array([-0.11679088,  0.05106821, -0.04204766,  2.05511926, -0.47593145,
        3.66056369, -0.01130402, -1.22769252,  0.2822199 , -0.01420304,
       -0.75517316,  0.01034618, -0.56551142])

# L2: Ridge Regression

In [8]:
boston = datasets.load_boston()

x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.1, random_state=4)

Ridge1 = Ridge(alpha = 0.5)

Ridge1.fit(x_train, y_train)

y_pred = Ridge1.predict(x_test)

MSE = mean_squared_error(y_test, y_pred)

r2 = r2_score(y_test, y_pred)

print("Mean squared error: ", MSE)
print("r2 score: ", r2)

Mean squared error:  17.19813153099512
r2 score:  0.7906678002423021


In [9]:
Ridge1.coef_

array([-1.23704175e-01,  4.91159855e-02, -6.54292956e-04,  2.97459634e+00,
       -1.27150162e+01,  3.65205272e+00, -2.04264365e-03, -1.42796092e+00,
        3.08584026e-01, -1.30340894e-02, -8.79495603e-01,  9.73637228e-03,
       -5.39665257e-01])

In [10]:
Ridge2 = Ridge(alpha = 0.05)

Ridge2.fit(x_train, y_train)

y_pred = Ridge2.predict(x_test)

MSE = mean_squared_error(y_test, y_pred)

r2 = r2_score(y_test, y_pred)

print("Mean squared error: ", MSE)
print("r2 score: ", r2)

Mean squared error:  17.051917883025983
r2 score:  0.7924474833729268


In [11]:
Ridge2.coef_

array([-1.25571175e-01,  4.85140353e-02,  1.58927465e-02,  3.07210574e+00,
       -1.67213053e+01,  3.62182362e+00,  1.63049147e-03, -1.48497894e+00,
        3.18457364e-01, -1.27683381e-02, -9.21126770e-01,  9.53907253e-03,
       -5.34353363e-01])